<?php if ($this->pageCount): ?>
	<div class="pagerSC">

		<!-- previous page link -->
		<?php if (isset($this->previous)): ?>
			<a href="<?php echo $this->url(array('page' => $this->previous)); ?>">&lt; Previous</a>
		<?php else: ?>
			<span>&lt; Previous</span>
		<?php endif; ?>

		<!-- numbered page links -->
		<?php foreach ($this->pagesInRange as $page): ?>
			<?php if ($page != $this->current): ?>
				<a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
			<?php else: ?>
				<span class="currentSC"><?php echo $page; ?></span>
			<?php endif; ?>
		<?php endforeach; ?>

		<!-- next page link -->
		<?php if (isset($this->next)): ?>
			<a href="<?php echo $this->url(array('page' => $this->next)); ?>">Next &gt;</a>
		<?php else: ?>
			<span>Next &gt;</span>
		<?php endif; ?>
		<div style="clear: left;"></div>
	</div>
<?php endif; ?>