<!-- fenetre -->
<div id="popup_editClient" class="popup_block overlay-fenetre">
	<!-- entete -->
	<header class="overlay-fenetre-titre">
			<span>Ajout d'un client</span>
	</header>
	<!-- formulaire -->
	<section class="overlay-fenetre-section">
		<div id="infoBulle1"><a href="#?ajoutSociete" rel="popup_ajoutSociete" class="poplight">Ajouter une société</a></div>
		<div id="infoBulle"></div>
		<?php echo $this->formClient; ?>
	</section>
</div>