<!-- titre de l'application -->
<div class="header_titre">
    <h2 class="section_title">application crm</h2>
</div>
<!-- titre de l'application ends here -->
<?php
	// si un utilisateur est authentifier
	if (Zend_Auth::getInstance ()->hasIdentity ()){
		?>
			<!-- bouton de deconnexion -->
			<div class="header_deconnexion">
			    <a href="<?php echo $this->baseUrl('login/deconnexion'); ?>" class="bouton" title="Déconnexion "><div id="deconnexion"></div></a>
			</div>
			<!-- bouton de deconnexion ends here -->
		<?php
	}
?>