<?php echo $this->doctype(), PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
    <head>
        <?php
            $this->headMeta()   ->setHttpEquiv('Content-Type', 'text/html;X charset=utf-8')
                                ->setHttpEquiv('Content-Style-Type', 'text/css')
                                ->setHttpEquiv('lang', 'fr')
                                // ->setHttpEquiv('Refresh', '2')
                                ->setName('author', 'Arnaud Lefevre')
                                ->setName('language', 'fr');
            echo $this->headMeta();

            $this->headLink()   ->appendStylesheet('/css/resetcss.css')
                                ->appendStylesheet('/css/styles.css')
                                ->appendStylesheet('/css/paginator.css')
                                ->appendStylesheet('/css/overlay.css')
                                ->appendStylesheet('/css/vader/jquery-ui-1.9.1.custom.css')
                                ->appendStylesheet('http://fonts.googleapis.com/css?family=PT+Sans+Narrow%7CPT+Sans%3Ai%2Cb%2Cbi&#038;ver=3.4.2');
            echo $this->headLink();
            

            // $this->JQuery() ->enable()
            //                 ->setVersion('1.8.3')
            //                 ->setUiVersion('1.9.2');

            $this->JQuery() ->enable()
                            ->setLocalPath('/js/jquery-1.8.3.js')
                            ->setUILocalPath('/js/jquery-ui-1.9.2.custom.min.js');

            echo $this  ->JQuery();

            $this->headScript() //->appendFile('/js/jquery.ui.datepicker-fr.js')
                                ->appendFile('/js/jquery.easing.1.3.js')
                                ->appendFile('/js/ajax.js')
                                ->appendFile('/js/overlay.js')
                                ->appendFile('/js/custom.js');
            echo $this->headScript();


        ?>
        <title>CRM</title>
</head> 
<!-- Header ends here -->

<body>
    <div id="fade"></div>
    <div class="body-page">
        <div id="page">
                 <!-- Navigation starts here -->     
                <nav id="menu_wrap">
                    <?php // echo $this->layout()->menu; ?>
                    <?php echo $this->action('afficher','menu'); ?>
                </nav>
                <!-- Navigation ends here -->

                <!-- Main wrap -->
                <div id="main_wrap">
                    <!-- Main -->
                    <div id="main">

                        <!-- Header -->
                        <header id="header">
                            <?php echo $this->partial('header.phtml'); ?>
                        </header>
                        <!-- Header ends here -->

                        <!-- Content -->
                        <section id="content">
                            <?php echo $this->layout()->content; ?>
                        </section>
                        <!-- Content ends here -->

                        <!-- Footer -->
                        <footer id="footer">
                            <?php
                                $registre = Zend_Registry::getInstance();
                                echo $this->partial('footer.phtml', array('annee' => $registre->config->app->copyright->annee));
                            ?>
                        </footer>
                        <!-- Footer ends here -->

                    </div>
                    <!-- main ends here -->
                </div>
                <!-- main wrap ends here -->
        </div>
    </div>
</body>
</html>